In [2]:
import pandas as pd
import numpy as np

#I still need to save these cleaned bits of data as new csv/text files.

In [111]:
#The following is a group of dataframes cleaned by Juls Marino for Team-82.

df1 = pd.read_csv('EDGE_ACS_CWIFT2018_State.txt', sep = '\t', header=None) #This is the data by State.

#The CWIFT measures wage and salary differences for college graduates. 
#The CWIFT for each location isthe predicted wage level for that location divided by the
# national average predicted wage,
df1.columns = ['ST_FIPS','ST_NAME','ST_CWIFTEST', 'ST_CWIFTSE']
#So we can call certain columns by name.

df1['ST_CWIFTEST'] = pd.to_numeric(df1['ST_CWIFTEST'],errors='coerce')
df1['ST_CWIFTSE'] = pd.to_numeric(df1['ST_CWIFTSE'],errors='coerce')
#This will help us use these values as floats, not string objects.

df1 = df1.rename(columns={'ST_NAME':'State', 'ST_CWIFTEST':'CWIFTEST_Score', 
                          'ST_CWIFTSE':'CWIFTEST_Standard_Error'})


df1.drop(df1.index[0], axis=0)
#This is meant to drop the first row so the column names aren't duplicated,
#but it isn't working yet. Hence the 'NaN' in the first row.

df1.drop(columns='ST_FIPS', inplace=True) 
#This is the two-digit Federal Information Processing Standard (FIPS)
#code for the state, which we don't need.

df1 = df1.set_index('State')
#This will make it easier to index by state name.


df1

                      CWIFTEST_Score  CWIFTEST_Standard_Error
State
ST_NAME                          NaN                      NaN
Alabama                        0.886                    0.004
Alaska                         1.021                    0.012
Arizona                        0.957                    0.004
Arkansas                       0.896                    0.005
California                     1.166                    0.002
Colorado                       0.974                    0.003
Connecticut                    1.074                    0.005
Delaware                       0.997                    0.008
District of Columbia           1.283                    0.006
Florida                        0.905                    0.002
Georgia                        0.970                    0.003
Hawaii                         1.016                    0.008
Idaho                          0.836                    0.008
Illinois                       1.026                    0.002
Indiana                        0.881                    0.003
Iowa                           0.886                    0.004
Kansas                         0.868                    0.004
Kentucky                       0.859                    0.004
Louisiana                      0.900                    0.005
Maine                          0.868                    0.006
Maryland                       1.084                    0.004
Massachusetts                  1.094                    0.003
Michigan                       0.919                    0.003
Minnesota                      1.007                    0.003
Mississippi                    0.837                    0.008
Missouri                       0.891                    0.003
Montana                        0.811                    0.008
Nebraska                       0.873                    0.004
Nevada                         0.994                    0.007
New Hampshire                  0.955                    0.006
New Jersey                     1.088                    0.004
New Mexico                     0.908                    0.007
New York                       1.141                    0.002
North Carolina                 0.928                    0.003
North Dakota                   0.892                    0.008
Ohio                           0.913                    0.002
Oklahoma                       0.878                    0.004
Oregon                         0.977                    0.005
Pennsylvania                   0.948                    0.003
Rhode Island                   0.994                    0.008
South Carolina                 0.880                    0.004
South Dakota                   0.813                    0.007
Tennessee                      0.893                    0.004
Texas                          0.993                    0.002
Utah                           0.913                    0.005
Vermont                        0.878                    0.008
Virginia                       1.033                    0.002
Washington                     1.092                    0.004
West Virginia                  0.812                    0.005
Wisconsin                      0.913                    0.003
Wyoming                        0.875                    0.012

In [117]:
#Had to do the following to open the second datafile.
import chardet
with open('EDGE_ACS_CWIFT2018_County.txt', 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

df2 = pd.read_csv('EDGE_ACS_CWIFT2018_County.txt', sep = '\t', encoding = 'ISO-8859-1')

df2.drop(columns='CNTY_FIPS', inplace=True) 
#This is the Federal Information Processing Standard (FIPS) code for the state, 
#which we don't need.

df2.drop(columns='MKT2015', inplace=True)
#This is the local labor market code for each county, 
#which we don't need.

df2['CNTY_CWIFTEST'] = pd.to_numeric(df2['CNTY_CWIFTEST'],errors='coerce')
df2['CNTY_CWIFTSE'] = pd.to_numeric(df2['CNTY_CWIFTSE'],errors='coerce')
#This will help us use these values as floats, not string objects.

df2 = df2.rename(columns={'CNTY_NAME':'County', 'ST_NAME':'State', 
                          'CNTY_CWIFTEST':'CWIFTEST_Score', 'CNTY_CWIFTSE': 'CWIFTEST_Standard_Error'})

df2 = df2.set_index('State')
#This will make it easier to index by state name.

#df2.isna().sum().sum() 
#This told me there were 0 missing pieces of data. 
df2

#We can use the following to see which counties have the CWIFTEST scores most highly correlated to poverty.
#df2[df2.CWIFTEST_Score <= .7]

                    County  CWIFTEST_Score  CWIFTEST_Standard_Error
State
Alabama     Autauga County           0.821                    0.033
Alabama     Baldwin County           0.824                    0.025
Alabama     Barbour County           0.907                    0.036
Alabama        Bibb County           0.812                    0.047
Alabama      Blount County           0.820                    0.030
...                    ...             ...                      ...
Wyoming  Sweetwater County           0.939                    0.066
Wyoming       Teton County           0.967                    0.045
Wyoming       Uinta County           0.814                    0.036
Wyoming    Washakie County           0.861                    0.040
Wyoming      Weston County           0.833                    0.036

[3142 rows x 3 columns]

In [4]:
df3 = pd.read_csv('EDGE_ACS_CWIFT2018_LEA1819.txt', sep = '\t', encoding = 'ISO-8859-1')

df3.drop(columns='LEAID', inplace=True) 
#This is the LEAID code, which uniquely identifies each local education agency (LEA) in 
#the CCD database, but we don't need it.


df3['LEA_CWIFTEST'] = pd.to_numeric(df3['LEA_CWIFTEST'],errors='coerce')
df3['LEA_CWIFTSE'] = pd.to_numeric(df3['LEA_CWIFTSE'],errors='coerce')
#This will help us use these values as floats, not string objects.

df3 = df3.rename(columns={'LEA_NAME':'District', 'ST_NAME':'State', 
                          'LEA_CWIFTEST':'CWIFTEST_Score', 'LEA_CWIFTSE': 'CWIFTEST_Standard_Error'})

df3 = df3.set_index('State')
#This will make it easier to index by state name.

#df3.isna().sum().sum() 
#df3.isnull().sum().sum()
#This told me there were 0 missing pieces of data.

0